Develop
nishikawa-na/my_app pull request #6
Opened 2024-07-16 09:54 UTC by nishikawa-na

## ER図の確認をお願いいたします。

https://drive.google.com/file/d/1ZuqENoHK86UPkDyqek4P9yIwNPneaELs/view?usp=sharing

2024-07-16 10:49 UTC, rdhdchloe commented
ご対応ありがとうございます！
以下コメンになります。

---

再提出する際スクショも貼って頂ければ助かります！

・`like_posts`に`post_id`が必要だと思いますがいかがでしょうか。
・フォロー機能 、投稿の閲覧数表示、通知など本リリースの各機能のテーブルも追加してください。

ご確認お願いします！

2024-07-18 01:26 UTC, Tsuchiya2 commented
Google driveでER図、閲覧できるのを確認しました。
ただURLを共有してレビューするやり方より、このプルリクエスト内で画像をアップすることが一般的なやり方かと思いますので、そちらを今のうちから身につけておいた方が良いかと思うので、以下の対応をお願いできますでしょうか。

- GyazoでER図のスクリーンショットを取る
- Gyazoの画面が開いたら「シェア」→「マークダウン」をクリックしてコピーを実施
- コピーしたものをプルリクエスト上の新しいコメント欄に投稿

上記を行っていただくことで、他の講師もER図の変遷が分かるようになるため、対応をお願いいたします。

2024-07-18 08:29 UTC, nishikawa-na commented
[![Image from Gyazo](https://i.gyazo.com/18acec1822b7e253ff3441068396508c.png)](https://gyazo.com/18acec1822b7e253ff3441068396508c)
こちらER図になります。

2024-07-18 10:22 UTC, tarakish requested changes
ご対応ありがとうございます。
以下コメントです！

---

- 共通
  - 各カラムについてデータ型の記載もお願いします。

- users
  - 認証にはなにかgemを使う想定でしょうか？
  - instagram_accountはカラムから名前が入るのかURLが入るのか想定が難しいのでそれが分かる命名にできるとベターかと思います。

- post_counts
  - こちらははユーザーごとの投稿数のカウントのためのテーブルでしょうか？
    - であれば多対多の関係性ではなさそうに思いました
- potos
  - photosでしょうか？

2024-07-18 13:21 UTC, nishikawa-na commented
下記修正を行いました。
・データ型を追記しました
・instagram_accountの名前を変更しました。
・photosに修正しました

説明
・認証はsorceryを使うことを想定しています。
・post_countsにつきまして
各postsのshowページにアクセスした時の
post_idとuser_idをpost_countに登録するためのテーブルです。

[![Image from Gyazo](https://i.gyazo.com/02d08deb2fd1208a9e04d91e1dcea434.png)](https://gyazo.com/02d08deb2fd1208a9e04d91e1dcea434)

2024-07-19 01:23 UTC, tmtkzk0823 commented
修正ありがとうございます。
概ね良さそうです。
LGTMです！

2024-07-19 10:22 UTC, merged